/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laporan;
import config.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class LaporanBulanan extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    DefaultTableModel model;

    /**
     * Creates new form LaporanBulanan
     */
    public LaporanBulanan() {
        initComponents();

        conn = new Koneksi().connect();

        setLocationRelativeTo(null);
        setTitle("Laporan Bulanan");

        model = new DefaultTableModel(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        model.addColumn("ID");
        model.addColumn("Komputer");
        model.addColumn("Pelanggan");
        model.addColumn("Waktu Mulai");
        model.addColumn("Waktu Selesai");
        model.addColumn("Durasi (menit)");
        model.addColumn("Total Bayar");
        tblLaporan.setModel(model);

        LocalDate now = LocalDate.now();
        cbBulan.setSelectedIndex(now.getMonthValue()-1);
        txtTahun.setText(String.valueOf(now.getYear()));

        tampilLaporan();
    }

    private void tampilLaporan(){

        model.setRowCount(0);
        double total = 0;

        try{

            int bulan = cbBulan.getSelectedIndex()+1;
            int tahun = Integer.parseInt(txtTahun.getText());

            String sql = "SELECT t.id_transaksi, k.nomor_komputer, "
                    + "COALESCE(p.nama_pelanggan,'Umum') AS nama_pelanggan, "
                    + "t.waktu_mulai, t.waktu_selesai, t.durasi_menit, t.total_bayar "
                    + "FROM tb_transaksi t "
                    + "JOIN tb_komputer k ON t.id_komputer = k.id_komputer "
                    + "LEFT JOIN tb_pelanggan p ON t.id_pelanggan = p.id_pelanggan "
                    + "WHERE MONTH(t.waktu_mulai) = ? AND YEAR(t.waktu_mulai) = ? AND t.status_transaksi = 'Selesai' "
                    + "ORDER BY t.id_transaksi";

            pst = conn.prepareStatement(sql);
            pst.setInt(1, bulan);
            pst.setInt(2, tahun);

            rs = pst.executeQuery();

            while(rs.next()){

                model.addRow(new Object[]{

                    rs.getString("id_transaksi"),
                    rs.getString("nomor_komputer"),
                    rs.getString("nama_pelanggan"),
                    rs.getString("waktu_mulai"),
                    rs.getString("waktu_selesai"),
                    rs.getString("durasi_menit"),
                    rs.getString("total_bayar")

                });

                total += rs.getDouble("total_bayar");

            }

            lblTotal.setText("Total Pendapatan: Rp " + total);

        }catch(NumberFormatException nfe){

            JOptionPane.showMessageDialog(null,"Tahun harus berupa angka!");

        }catch(Exception e){

            JOptionPane.showMessageDialog(null,e);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbBulan = new javax.swing.JComboBox<>();
        txtTahun = new javax.swing.JTextField();
        btnTampilkan = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLaporan = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Bulan");
        jLabel2.setText("Tahun");

        cbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember" }));

        btnTampilkan.setText("Tampilkan");
        btnTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanActionPerformed(evt);
            }
        });

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(tblLaporan);

        lblTotal.setText("Total Pendapatan: Rp 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6,6,6)
                        .addComponent(cbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15,15,15)
                        .addComponent(jLabel2)
                        .addGap(6,6,6)
                        .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15,15,15)
                        .addComponent(btnTampilkan)
                        .addGap(10,10,10)
                        .addComponent(btnCetak)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1).addComponent(cbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2).addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTampilkan).addComponent(btnCetak))
                .addGap(15,15,15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12,12,12)
                .addComponent(lblTotal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanActionPerformed
        // TODO add your handling code here:
        tampilLaporan();
    }//GEN-LAST:event_btnTampilkanActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:

        StringBuilder sb = new StringBuilder();
        sb.append("LAPORAN BULANAN WARNET\n");
        sb.append("Bulan/Tahun: ").append(cbBulan.getSelectedItem()).append(" ").append(txtTahun.getText()).append("\n");
        sb.append("======================================================\n");
        sb.append(String.format("%-5s %-12s %-15s %-20s %-10s%n","ID","Komputer","Pelanggan","Waktu Mulai","Total"));
        sb.append("------------------------------------------------------\n");

        for(int i=0;i<model.getRowCount();i++){
            sb.append(String.format("%-5s %-12s %-15s %-20s %-10s%n",
                    model.getValueAt(i,0),
                    model.getValueAt(i,1),
                    model.getValueAt(i,2),
                    model.getValueAt(i,3),
                    model.getValueAt(i,6)));
        }

        sb.append("======================================================\n");
        sb.append(lblTotal.getText());

        new CetakLaporan("Laporan Bulanan", sb.toString()).setVisible(true);
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanBulanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanBulanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanBulanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanBulanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanBulanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnTampilkan;
    private javax.swing.JComboBox<String> cbBulan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblLaporan;
    private javax.swing.JTextField txtTahun;
    // End of variables declaration//GEN-END:variables
}
