/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package transaksi;
import config.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class RiwayatTransaksi extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    DefaultTableModel model;

    /**
     * Creates new form RiwayatTransaksi
     */
    public RiwayatTransaksi() {
        initComponents();

        conn = new Koneksi().connect();

        setLocationRelativeTo(null);
        setTitle("Riwayat Transaksi");

        model = new DefaultTableModel(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        model.addColumn("ID");
        model.addColumn("Komputer");
        model.addColumn("Pelanggan");
        model.addColumn("Tarif");
        model.addColumn("Waktu Mulai");
        model.addColumn("Waktu Selesai");
        model.addColumn("Durasi (menit)");
        model.addColumn("Total Bayar");
        model.addColumn("Status");
        model.addColumn("Status Bayar");
        tblRiwayat.setModel(model);

        tampilSemua();
    }

    private void tampilSemua(){

        model.setRowCount(0);

        try{

            String sql = "SELECT t.id_transaksi, k.nomor_komputer, "
                    + "COALESCE(p.nama_pelanggan,'Umum') AS nama_pelanggan, "
                    + "tr.nama_tarif, t.waktu_mulai, t.waktu_selesai, t.durasi_menit, "
                    + "t.total_bayar, t.status_transaksi, t.status_bayar "
                    + "FROM tb_transaksi t "
                    + "JOIN tb_komputer k ON t.id_komputer = k.id_komputer "
                    + "LEFT JOIN tb_pelanggan p ON t.id_pelanggan = p.id_pelanggan "
                    + "JOIN tb_tarif tr ON t.id_tarif = tr.id_tarif "
                    + "ORDER BY t.id_transaksi DESC";

            pst = conn.prepareStatement(sql);

            rs = pst.executeQuery();

            isiTabel();

        }catch(Exception e){

            JOptionPane.showMessageDialog(null,e);

        }
    }

    private void isiTabel() throws Exception{

        while(rs.next()){

            model.addRow(new Object[]{

                rs.getString("id_transaksi"),
                rs.getString("nomor_komputer"),
                rs.getString("nama_pelanggan"),
                rs.getString("nama_tarif"),
                rs.getString("waktu_mulai"),
                rs.getString("waktu_selesai"),
                rs.getString("durasi_menit"),
                rs.getString("total_bayar"),
                rs.getString("status_transaksi"),
                rs.getString("status_bayar")

            });

        }
    }

    private void cariBerdasarkanTanggal(){

        if(txtDari.getText().isEmpty() || txtSampai.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Isi tanggal Dari dan Sampai (format: yyyy-MM-dd)!");
            return;
        }

        model.setRowCount(0);

        try{

            String sql = "SELECT t.id_transaksi, k.nomor_komputer, "
                    + "COALESCE(p.nama_pelanggan,'Umum') AS nama_pelanggan, "
                    + "tr.nama_tarif, t.waktu_mulai, t.waktu_selesai, t.durasi_menit, "
                    + "t.total_bayar, t.status_transaksi, t.status_bayar "
                    + "FROM tb_transaksi t "
                    + "JOIN tb_komputer k ON t.id_komputer = k.id_komputer "
                    + "LEFT JOIN tb_pelanggan p ON t.id_pelanggan = p.id_pelanggan "
                    + "JOIN tb_tarif tr ON t.id_tarif = tr.id_tarif "
                    + "WHERE DATE(t.waktu_mulai) BETWEEN ? AND ? "
                    + "ORDER BY t.id_transaksi DESC";

            pst = conn.prepareStatement(sql);
            pst.setString(1, txtDari.getText());
            pst.setString(2, txtSampai.getText());

            rs = pst.executeQuery();

            isiTabel();

        }catch(Exception e){

            JOptionPane.showMessageDialog(null,e);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDari = new javax.swing.JTextField();
        txtSampai = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnSemua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRiwayat = new javax.swing.JTable();
        btnTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Dari (yyyy-MM-dd)");
        jLabel2.setText("Sampai (yyyy-MM-dd)");

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnSemua.setText("Tampilkan Semua");
        btnSemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSemuaActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(tblRiwayat);

        btnTutup.setText("Tutup");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6,6,6)
                        .addComponent(txtDari, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15,15,15)
                        .addComponent(jLabel2)
                        .addGap(6,6,6)
                        .addComponent(txtSampai, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15,15,15)
                        .addComponent(btnCari)
                        .addGap(10,10,10)
                        .addComponent(btnSemua)
                        .addGap(10,10,10)
                        .addComponent(btnTutup)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1).addComponent(txtDari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2).addComponent(txtSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari).addComponent(btnSemua).addComponent(btnTutup))
                .addGap(15,15,15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        cariBerdasarkanTanggal();
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSemuaActionPerformed
        // TODO add your handling code here:
        tampilSemua();
    }//GEN-LAST:event_btnSemuaActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiwayatTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiwayatTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiwayatTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiwayatTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RiwayatTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnSemua;
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRiwayat;
    private javax.swing.JTextField txtDari;
    private javax.swing.JTextField txtSampai;
    // End of variables declaration//GEN-END:variables
}
